name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install liblilv-dev lv2-examples mda-lv2 jackd libjack0 libjack-dev
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: crates.io Login
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo Token is $CARGO_REGISTRY_TOKEN
          cargo publish --token $CARGO_REGISTRY_TOKEN
